Repository theTaoTeam/snuze_app, pull requests merged in 2018-12, with the labels that each got.

#32 Alarmdisplayscreen
  .gitignore
  .idea/libraries/KotlinJavaRuntime.xml
  android/.idea/caches/build_file_checksums.ser
  android/.idea/gradle.xml
  android/.idea/misc.xml
  android/.idea/modules.xml
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Pods.xcodeproj/xcuserdata/westonharper.xcuserdatad/xcschemes/Bolts.xcscheme
  ios/Pods/Pods.xcodeproj/xcuserdata/westonharper.xcuserdatad/xcschemes/FBSDKCoreKit.xcscheme
  ios/Pods/Pods.xcodeproj/xcuserdata/westonharper.xcuserdatad/xcschemes/FBSDKLoginKit.xcscheme
  ios/Pods/Pods.xcodeproj/xcuserdata/westonharper.xcuserdatad/xcschemes/Pods-Runner.xcscheme
  ios/Pods/Pods.xcodeproj/xcuserdata/westonharper.xcuserdatad/xcschemes/flutter_facebook_login.xcscheme
  ios/Pods/Pods.xcodeproj/xcuserdata/westonharper.xcuserdatad/xcschemes/shared_preferences.xcscheme
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/xcuserdata/scottclampet.xcuserdatad/UserInterfaceState.xcuserstate
  ios/Runner.xcworkspace/xcuserdata/westonharper.xcuserdatad/UserInterfaceState.xcuserstate
  ios/Runner.xcworkspace/xcuserdata/westonharper.xcuserdatad/WorkspaceSettings.xcsettings
  ios/Runner/song.caf
  lib/main.dart
  lib/pages/home/alarm_settings.dart
  lib/pages/snuze/snuze.dart
  lib/scoped-models/alarm.dart
Labels: feature, improvement

#37 feat(settings): update resetpassword option so it uses firebase sdk
  lib/pages/settings/settings.dart
  lib/scoped-models/user.dart
Labels: feature

#41 fix(forgot_password): update auth forgot pass to use firebase sdk
  lib/pages/auth/forgot_password.dart
Labels: bug

#45 feat(auth, signup, auth action buttons): added isLoading bool in user…
  lib/pages/auth/actions/login_action_buttons.dart
  lib/pages/auth/actions/signup_actions.dart
  lib/pages/auth/auth.dart
  lib/pages/auth/forgot_password.dart
  lib/pages/auth/signup.dart
  lib/scoped-models/user.dart
Labels: feature, improvement
